export const symbolMapper = [
    "bauble",
    "bell",
    "candy-cane",
    "christmas-tree",
    "gingerbread-man",
    "hat",
    "holly",
    "penguin",
    "present",
    "reindeer",
    "robin",
    "santa",
    "snowflake",
    "snowman",
    "sock",
    "star",
    "symbols"
]